INSERT INTO roles(role_name) VALUES
('ROLE_USER'), ('ROLE_ADMIN');

INSERT INTO topics(theme) VALUES
('security'),('investment'),('games'),
('literature'),('cinema'),('pets'),
('cars'),('programming'),('building'),
('collectioning'),('art'),('survivalism'),
('architecture'),('tabletop games'),('cartoons'),
('charity');

INSERT INTO tags(name) VALUES
('Ankunding and Sons'),
('Smith, Schuster and Kunde'),
('Hudson, Ratke and Lemke'),
('Franecki-Bergstrom'),
('Koch, Goldner and Bednar'),
('Tremblay, Smith and Weissnat'),
('Quitzon Group'),
('Bogan Group'),
('Hilll, Emard and Jacobson'),
('Emard, Hauck and Schuppe'),
('Wehner LLC'),
('Hauck-Mante'),
('Herzog, Kilback and Lind'),
('Bergnaum-Labadie'),
('Spencer-Denesik'),
('Ondricka LLC'),
('Barton Inc'),
('Wisoky-Littel'),
('Stokes-Paucek'),
('Rosenbaum Inc'),
('Smitham, Simonis and Feil'),
('Kunze-Gerlach'),
('Price, Boyle and Adams'),
('Fisher-Gottlieb'),
('Collins, Bechtelar and Rath'),
('Nolan-Bartell'),
('Lehner-OConner'),
('Walker, Steuber and Dietrich'),
('Mills Group'),
('Klocko, Cruickshank and DuBuque'),
('Heller-Labadie'),
('Purdy Inc'),
('Fritsch-Volkman'),
('Buckridge and Sons'),
('Green-Zemlak'),
('Lemke Group'),
('Schinner, MacGyver and Gorczany'),
('Schuppe, Beier and Reilly'),
('Hodkiewicz LLC'),
('Stiedemann-McKenzie'),
('Friesen-Raynor'),
('Frami-Hills'),
('Waters Group'),
('Gottlieb-Hamill'),
('Abshire-Kihn'),
('Langosh and Sons'),
('Bergnaum-Oberbrunner'),
('Littel, Kirlin and Schimmel'),
('Kihn-Gutkowski'),
('Wisozk, Douglas and Emmerich'),
('Funk, Pagac and Wisozk'),
('Pacocha, Hermann and Adams'),
('Goodwin-Jenkins'),
('Morar-Romaguera'),
('Schimmel-Schimmel'),
('Gislason, Hermann and Grimes'),
('Terry, Wehner and Klocko'),
('Swaniawski-Reinger'),
('Friesen Inc'),
('Grant-Oberbrunner'),
('Herman Inc'),
('Heller, Swift and Leuschke'),
('Sauer, Kshlerin and Dibbert'),
('Turcotte LLC'),
('Schroeder Group'),
('Emard-Mills'),
('Mayer, Farrell and Weimann'),
('Carroll, Tillman and Johns'),
('Kuphal, Bahringer and Roob'),
('Kessler, Thiel and Kunde'),
('Marquardt and Sons'),
('Runolfsson and Sons'),
('Ziemann-Johns'),
('Kemmer Inc'),
('Mraz-Bradtke'),
('Sipes and Sons'),
('Bernhard-Carter'),
('Williamson Inc'),
('Zulauf, MacGyver and Veum'),
('Casper, Weber and Cruickshank'),
('Hansen-Schoen'),
('Cole, Konopelski and Howe'),
('Stracke-Rohan'),
('Davis Inc'),
('Marvin, Lesch and Jones'),
('Smitham, Hansen and Heaney'),
('Rempel, Johnston and Kiehn'),
('Feest Group'),
('Roob Group'),
('Bogan, Lemke and Glover'),
('Carter, Walter and Gaylord'),
('Hauck, Rippin and Runolfsdottir'),
('Dietrich, Bode and Wolff'),
('West-Casper'),
('McKenzie-Morissette'),
('Krajcik Inc'),
('Hane, Haag and Walker'),
('Jacobi-Jacobson'),
('Wintheiser, McKenzie and Raynor'),
('Pouros-Bradtke');

/*admin generation*/
INSERT INTO users(user_id, name, email, password, is_enabled) VALUES ('200', 'MainAdmin', 'mainadmin@gmail.com', '$2a$10$Rl90dAMRDnzRZl1MaXWPQOmZV563fsRzH83KdjX0ZRm1Tnu8NH7/W', 'true');
INSERT INTO users_roles(user_id, role_id) VALUES ('200', '2');
